// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

namespace backend.Migrations
{
    [DbContext(typeof(EfDbContext))]
    [Migration("20190418200020_primeiro12")]
    partial class primeiro12
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("backend.Model.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf")
                        .IsRequired();

                    b.Property<DateTime>("Nascimento");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<int?>("ProfissaoIdProfissao");

                    b.Property<string>("Sobrenome")
                        .IsRequired();

                    b.HasKey("IdCliente");

                    b.HasIndex("ProfissaoIdProfissao");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("backend.Model.Profissao", b =>
                {
                    b.Property<int>("IdProfissao")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.HasKey("IdProfissao");

                    b.ToTable("Profissoes");
                });

            modelBuilder.Entity("backend.Model.Cliente", b =>
                {
                    b.HasOne("backend.Model.Profissao", "Profissao")
                        .WithMany()
                        .HasForeignKey("ProfissaoIdProfissao");
                });
#pragma warning restore 612, 618
        }
    }
}
